version: "3.8"

services:

  mysql:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "3307:3306"
    restart: always
    networks:
      - mired


  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 
    networks:
      - mired

  wordpress:
    depends_on:
     - mysql
    image: wordpress:latest
    volumes:
     - ./html:/var/www/html/
    ports:
      - "8002:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: 172.17.0.1:3307
      WORDPRESS_DB_USER: 
      WORDPRESS_DB_PASSWORD: 
      WORDPRESS_DB_NAME: 
    links:
      - mysql
    networks:
      - mired
networks:
   mired:
      external: false
